apiVersion: v1
kind: Service
metadata:
 name: capstone
spec:
 selector:
 app: capstone-app
 ports:
 - protocol: "TCP"
 port: 6000
 targetPort: 5000
 type: LoadBalancer
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: capstone-app
spec:
 selector:
 matchLabels:
 app: capstone-app
 replicas: 5
 template:
 metadata:
 labels:
    app: capstone-app
 spec:
 containers:
 - name: capstone-app
 image: suriya/webapp-capstone
 imagePullPolicy: IfNotPresent
 ports:
 - containerPort: 5000